Publish downtime messages sent by bot
HyacinthBots/Lily-watchdog pull request #2
Opened 2022-11-30 02:51 UTC by CaioMGT

Noticed this earlier, tested working on announcement channels

2022-11-30 07:40 UTC, NoComment1105 requested changes
You'll need to do some extra verification to find out if the channels are actually announcement channels, since I've left the ability to use any channel, theres a chance it will just raise an exception

2022-11-30 12:16 UTC, tempest15 commented
It would be nice if the publishing was a config option when setting the  bot to be watched, but you would still need to check later as well

2022-11-30 21:52 UTC, CaioMGT reviewed
Fixed

2022-11-30 21:59 UTC, NoComment1105 requested changes
Nearly there, very good

2022-11-30 21:59 UTC, NoComment1105 commented on src/main/kotlin/org/hyacinthbots/saffronstatus/database/migrations/v1.kt
>  	// TODO Fill with migration and set true in main function
🦀  this

2022-11-30 21:59 UTC, NoComment1105 commented on src/main/kotlin/org/hyacinthbots/saffronstatus/database/migrations/v1.kt
> +			)
Some strange indentation afoot here. Try ctrl + alt + L or the below
```suggestion
			WatchedBotData::publishMessage exists false,
			setValue(WatchedBotData::publishMessage, false)
```

2022-12-01 15:03 UTC, tempest15 commented on src/main/kotlin/org/hyacinthbots/saffronstatus/extensions/WatchedBot.kt
> +			description = "Whether to publish the downtime messages for this bot"
```suggestion
			description = "If downtime messages sent in announcement channels should be published"
```

2022-12-01 16:05 UTC, tempest15 approved these changes
LGTM, we'll wait for NC to merge

2022-12-01 16:53 UTC, NoComment1105 approved these changes

2022-12-02 09:47 UTC, NoComment1105 commented
Apparently never merged this lmao

2022-12-02 09:47 UTC, merged